$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json

name: blue
endpoint_name: cw2-endpoint

model: azureml:cw2-classification:3

environment:
  conda_file: environment.yml
  image: mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu20.04:latest

code_configuration:
  code: .
  scoring_script: score.py

instance_type: Standard_DS2_v2
instance_count: 1
