$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json

name: blue
endpoint_name: cw2-endpoint

model: azureml:cw2-regression-model:1   # UPDATE after registering your model

environment:
  image: mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu20.04:latest
  conda_file: pipelines/environment.yml

code_configuration:
  code: ./deployment
  scoring_script: score.py

instance_type: Standard_DS2_v2
instance_count: 1
